request:
    method: GET
    url: /validate/prime-number
    headers:
        Content-Type: application/json
    queryParameters:
        number: 5
response:
    status: 200
    headers:
        Content-Type: text/plain;charset=ISO-8859-1
    body: Odd