name: common-workflow-run

on:
  workflow_dispatch:
    inputs:
      run-sonar-scan:
        description: 'Sonar scan'
        required: false
        type: boolean
        default: true
      run-static-scan:
        description: 'static scan'
        required: false
        type: boolean
        default: true
      run-reload-test:
        description: 'Reload performance test'
        required: false
        type: boolean
        default: true
      reload-test-scenario:
        description: 'scenario name'
        type: choice
        required: false
        default: 1500-user-test
        options:
          - 1500-user-test
  push:
    branches:
      - main
jobs:
  run-common-test:
    uses: Meselu2/GitHub-action-workflow/.github/workflows/maven.yml@main
    with:
      app-name: 'springapplication_demo_newman'
      java-version: '17'
      run-sonar-scan: ${{inputs.run-sonar-scan || true}}
      run-static-scan: ${{inputs.run-static-scan || true}}
      run-reload-test: ${{inputs.run-reload-test || true}}
      reload-test-scenario: ${{inputs.reload-test-scenario}}

